name: study-buddy-ai
services:
  db:
    image: pgvector/pgvector:pg17
    restart: always
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
        POSTGRES_DB: study-buddy-ai
    ports:
        - "5432:5432"
    volumes:
        - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7.4-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  pg_data:
  redis-data:


