"""removed auth provider table

Revision ID: 0b7ecd0c24d2
Revises: 705c16f7c915
Create Date: 2026-04-13 17:36:31.065034

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0b7ecd0c24d2"
down_revision: Union[str, Sequence[str], None] = "705c16f7c915"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("auth_providers")
    op.add_column(
        "embeddings",
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.add_column(
        "files",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )
    op.add_column(
        "flashcards",
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.add_column(
        "quizzes", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("quizzes", "updated_at")
    op.drop_column("flashcards", "updated_at")
    op.drop_column("files", "updated_at")
    op.drop_column("embeddings", "updated_at")
    op.create_table(
        "auth_providers",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "provider_type",
            postgresql.ENUM("Google", "Email", name="providertype"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("provider_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("auth_providers_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("auth_providers_pkey")),
    )
    # ### end Alembic commands ###
