"""fixed typo

Revision ID: 4c4ade177e96
Revises: 86388ee62dac
Create Date: 2026-05-07 16:09:55.126708

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4c4ade177e96"
down_revision: Union[str, Sequence[str], None] = "86388ee62dac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("quizzes", sa.Column("option_1", sa.String(), nullable=True))
    op.add_column("quizzes", sa.Column("option_2", sa.String(), nullable=True))
    op.add_column("quizzes", sa.Column("option_3", sa.String(), nullable=True))
    op.add_column("quizzes", sa.Column("option_4", sa.String(), nullable=True))
    op.drop_column("quizzes", "Option_4")
    op.drop_column("quizzes", "Option_2")
    op.drop_column("quizzes", "Option_1")
    op.drop_column("quizzes", "Option_3")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "quizzes",
        sa.Column("Option_3", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "quizzes",
        sa.Column("Option_1", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "quizzes",
        sa.Column("Option_2", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "quizzes",
        sa.Column("Option_4", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("quizzes", "option_4")
    op.drop_column("quizzes", "option_3")
    op.drop_column("quizzes", "option_2")
    op.drop_column("quizzes", "option_1")
    # ### end Alembic commands ###
