"""added relatonship

Revision ID: 73a89e529194
Revises: a98636a71401
Create Date: 2026-05-07 18:18:52.082951

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "73a89e529194"
down_revision: Union[str, Sequence[str], None] = "a98636a71401"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
