"""added file_id

Revision ID: 86388ee62dac
Revises: ea9ea5a5f757
Create Date: 2026-05-06 23:32:01.723586

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "86388ee62dac"
down_revision: Union[str, Sequence[str], None] = "ea9ea5a5f757"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("flashcards", sa.Column("file_id", sa.Uuid(), nullable=True))
    op.add_column("flashcards", sa.Column("remember", sa.Boolean(), nullable=True))
    op.create_index(
        op.f("ix_flashcards_file_id"), "flashcards", ["file_id"], unique=False
    )
    op.create_foreign_key(
        None, "flashcards", "files", ["file_id"], ["id"], ondelete="CASCADE"
    )
    op.add_column("quizzes", sa.Column("file_id", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_quizzes_file_id"), "quizzes", ["file_id"], unique=False)
    op.create_foreign_key(
        None, "quizzes", "files", ["file_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "quizzes", type_="foreignkey")  # type: ignore
    op.drop_index(op.f("ix_quizzes_file_id"), table_name="quizzes")
    op.drop_column("quizzes", "file_id")
    op.drop_constraint(None, "flashcards", type_="foreignkey")  # type: ignore
    op.drop_index(op.f("ix_flashcards_file_id"), table_name="flashcards")
    op.drop_column("flashcards", "remember")
    op.drop_column("flashcards", "file_id")
    # ### end Alembic commands ###
