"""youtube table added

Revision ID: a98636a71401
Revises: 4c4ade177e96
Create Date: 2026-05-07 17:44:15.162222

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a98636a71401"
down_revision: Union[str, Sequence[str], None] = "4c4ade177e96"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "youtube_transcribe",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("transcript", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_youtube_transcribe_user_id"),
        "youtube_transcribe",
        ["user_id"],
        unique=False,
    )
    op.alter_column(
        "quizzes", "correct_option", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "quizzes", "correct_option", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_index(
        op.f("ix_youtube_transcribe_user_id"), table_name="youtube_transcribe"
    )
    op.drop_table("youtube_transcribe")
    # ### end Alembic commands ###
