"""embedding jobs table created

Revision ID: ea9ea5a5f757
Revises: 0b7ecd0c24d2
Create Date: 2026-04-19 18:36:55.396865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea9ea5a5f757'
down_revision: Union[str, Sequence[str], None] = '0b7ecd0c24d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
